// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Users.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260420020740_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Users.Domain.Users.Entities.SellerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SellerProfiles", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentiyProviderId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn", "Id");

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Models.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Code");

                    b.ToTable("Permissions", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Models.RegistrationTypeRoles", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("RoleName")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Type", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("RegistrationTypeRoles", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Models.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Name");

                    b.ToTable("Roles", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("RoleName")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("PermissionCode", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("RolePermissions", "users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("RoleName");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesName", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Entities.SellerProfile", b =>
                {
                    b.HasOne("Modules.Users.Domain.Users.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Modules.Users.Domain.Users.Entities.SellerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Modules.Users.Domain.Users.ValueObjects.Document", "Document", b1 =>
                        {
                            b1.Property<Guid>("SellerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("Document");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("DocumentType");

                            b1.HasKey("SellerProfileId");

                            b1.ToTable("SellerProfiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("SellerProfileId");
                        });

                    b.OwnsOne("Modules.Users.Domain.Users.ValueObjects.PaymentAccount", "PaymentAccount", b1 =>
                        {
                            b1.Property<Guid>("SellerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Agency")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("Agency");

                            b1.Property<string>("BankCode")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("BankCode");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("AccountNumber");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("AccountType");

                            b1.HasKey("SellerProfileId");

                            b1.ToTable("SellerProfiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("SellerProfileId");
                        });

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("PaymentAccount")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Entities.User", b =>
                {
                    b.OwnsOne("Modules.Users.Domain.Users.ValueObjects.Age", "Age", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("BirthDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BirthDate");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Modules.Users.Domain.Users.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("VARCHAR(160)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("IX_Users_Email");

                            b1.ToTable("Users", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Modules.Users.Domain.Users.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Age")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Users.Domain.Users.Models.RegistrationTypeRoles", b =>
                {
                    b.HasOne("Modules.Users.Domain.Users.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Modules.Users.Domain.Users.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Users.Domain.Users.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Modules.Users.Domain.Users.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Users.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
